services:
  app:
    build: .
    ports:
      - "3001:3001"
    container_name: email-forwarder
    environment:
      - IMAP_SERVER=your_imap_server
      - IMAP_PORT=143
      - IMAP_USER=your_mail_user
      - IMAP_PASSWORD=your_mail_password
      - API_URL=http:your_api_url
      - RECIPIENT_ID=your_wa_api_number
